### PR TITLE
Add metapackage names in README.md

### PR DESCRIPTION
**Pull request by ld991**
Fix issues #68 and #69. Mention metapackages and add links to their official websites in a new table column in README.md. Three metapackages are listed, namely, `FontForge` for `fontimage`, `ImageMagick` for `convert` and `Transmission` for `transmission-show`.

This helps users easily discover and install programs required for file previews for various filetypes.

### CODE REVIEW

**Comment by NikitaIvanovV** [comment]
Thank you!

If we are going to do this, it would make sense to add links for more programs (glow, libreoffice, chafa, etc...).

I do not think a new table column is needed, we could add links for these programs in the second table column. Some programs are listed is multiple places, so I recommend using reference-style links like this:

```markdown
[libreoffice][libreoffice]
[libreoffice][libreoffice]

[libreoffice]: https://www.libreoffice.org/
```

> [libreoffice][libreoffice]
> [libreoffice][libreoffice]

[libreoffice]: https://www.libreoffice.org/

**Comment by ld991** [comment]
Yes, that does make more sense. And I also noticed the table appear in various places.

The issue I'm intending to fix is programs like 'fontimage' and 'display'  rather than programs like 'librewolf' because for people who aren't already aware of the programs, even a Google search is unhelpful.

However, for the sake of consistency, adding a link to other programs also seems reasonable.

**Comment by ld991** [comment]
I removed the third table column and added links to almost all programs. The links were largely copied from Arch Linux package descriptions and include links to their websites or github projects.

**Comment by NikitaIvanovV** [comment]
> And I also noticed the table appear in various places.

I completely forgot about that it also appears in the man page. And it's also auto-generated from previewer files!

I will make a change to the scripts that produce the tables.

**Pull request closed without merging**
